{
  #host and port to deploy the container
  'host': '0.0.0.0',
  #'host': '172.21.0.1',
  'port': '5002',
  #port for the script dc_net.py which replicates the connection to NLP Chat
  'dc_port': '5001',
  #groq api key
  'groq_api_key': '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',

  #directories and files
  'current_user_file': 'current_user.csv',
  'policy_store_file': 'policy_store.csv',
  'processed_data_file': 'processed_data.txt',
  'retrieved_data_file': 'data_folder/retrieved_data.txt',
  'retrieved_data_folder': 'data_folder',

  #prefixes for the sparql query endpoint
  'prefixes': {
    "epo": "http://data.europa.eu/a4g/ontology#",
    "dct": "http://purl.org/dc/terms/"
  },
  #sparql endpoint and login details for basic authentication
  'sparql_endpoint': 'https://cyclops-dev.ontopic.dev/sparql-endpoint/uc3-mitender/sparql',
  'username': 'tubs',
  'password': 'RenfeokKinlaJis',


}

