version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_PASSWORD: password123
      MYSQL_DATABASE: cyclops
    #networks:
    #  - my_custom_network
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  ihu:
    build: .
    container_name: ihu
    #network_mode: "host"  # This allows direct access to host network
    ports:
      - "5002:5002"  # Ensure this matches the Flask app's port
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password123
      DB_NAME: cyclops
    command: ["python3", "-u", "main.py"]

volumes:
  mysql-data:
