#version: '3.8'

services:
  #minio for long term storage
  minio:
    image: quay.io/minio/minio
    container_name: my_minio
    networks:
      - docker_ihu_default
    ports:
      - "9100:9000"  # MinIO API on port 9100
      - "9101:9001"  # MinIO Console on port 9101
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    volumes:
      #- minio_data:/data
      - /data
    command: server /data --console-address ":9001"
    #command: /bin/bash -c "rm -rf /data/* && minio server /data" --console-address ":9001"


  #for mysql service to host the cyclops database
  mysql:
    image: mysql:latest
    container_name: mysql-container
    networks:
      - docker_ihu_default
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_PASSWORD: password123
      MYSQL_DATABASE: cyclops
    ports:
      - "3306:3306"
    volumes:
    #  - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Auto-run SQL script
    command: ["/bin/bash", "-c", "rm -rf /var/lib/mysql/* && docker-entrypoint.sh mysqld"]

  #for the ihu itself
  ihu:
    build: .
    container_name: ihu
    networks:
      - docker_ihu_default
    ports:
      - "5002:5002"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password123
      DB_NAME: cyclops
    command: ["python3", "-u", "main.py"]

#volumes:
#  mysql-data:
#  minio_data:
  # driver: local

networks:
  docker_ihu_default: