version: '3.8'

services:
  #for mysql service to host the cyclops database
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_PASSWORD: password123
      MYSQL_DATABASE: cyclops
    ports:
      - "3306:3306"
    volumes:
    #  - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Auto-run SQL script

  #for the ihu itself
  ihu:
    build: .
    container_name: ihu
    ports:
      - "5002:5002"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password123
      DB_NAME: cyclops
    command: ["python3", "-u", "main.py"]

#volumes:
#  mysql-data:
